name: Auto PR

on: create

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  pr:
    if: github.event.ref_type == 'branch' && ! github.event.repository.fork && ! contains(github.event.ref, '(WIP)')
    name: Create PR
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git
        run: |
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config user.name 'github-actions[bot]'
          git config --bool push.autoSetupRemote 1
      - name: Create a pull request
        shell: bash
        run: |
          if git diff --quiet origin/main; then
            git commit --allow-empty -m 'empty commit'
            git push
          fi
          gh pr create --draft --base main --assignee ${{ github.event.sender.login }} --title "${{ github.event.ref }}" --body "$(echo '${{ github.event.ref }}' | grep -oE '#[0-9]+' | xargs -I# echo 'close #' || echo 'issue なし')"
